#ifndef PDCM_STATUS_H_
#define PDCM_STATUS_H_

#include "pdcm/base.h"

PDCM_BEGIN_DECLS

typedef enum pdcm_status {
  PDCM_STATUS_SUCCESS = 0,
  PDCM_STATUS_PARTIAL_RESULT = 1,
  PDCM_STATUS_INVALID_ARGUMENT = 2,
  PDCM_STATUS_UNSUPPORTED = 3,
  PDCM_STATUS_NOT_INITIALIZED = 4,
  PDCM_STATUS_UNAVAILABLE = 5,
  PDCM_STATUS_PERMISSION_DENIED = 6,
  PDCM_STATUS_TIMEOUT = 7,
  PDCM_STATUS_RESOURCE_EXHAUSTED = 8,
  PDCM_STATUS_BUFFER_TOO_SMALL = 9,
  PDCM_STATUS_NOT_FOUND = 10,
  PDCM_STATUS_STALE_GENERATION = 11,
  PDCM_STATUS_INTERNAL = 12,
  PDCM_STATUS_PROTOCOL_INCOMPATIBLE = 13
} pdcm_status_t;

PDCM_END_DECLS

#endif // PDCM_STATUS_H_
